[web]
172.31.42.188 ansible_user=ec2-user

[db]
172.31.33.111 ansible_user=ec2-user

[all:vars]
ansible_ssh_private_key_file=~/.ssh/CL_onishi.pem
ansible_become=true
ansible_python_interpreter=/usr/bin/python3